/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import atlantafx.base.theme.Dracula;
import atlantafx.base.theme.PrimerDark;
import atlantafx.base.theme.PrimerLight;
import org.example.pages.ExamplePage;
import org.example.pages.ExampleTwoPage;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.jenvy.view.router.Page;

import java.util.Map;


public class App extends Application {
   private Session session;

    public static void main(String[] args) {
        
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        Class<?extends Page> defaultPage = ExamplePage.class;
        Map<String,Class<? extends Page>> map = Map
                .of(
                        "uno",ExamplePage.class,
                        "dos", ExampleTwoPage.class
                );

        org.jenvy.App app = new org.jenvy.App(map,defaultPage);


       
    
        primaryStage.setMaximized(true);
        String cssPath = getClass().getResource("/styles/style.css").toExternalForm();
        Application.setUserAgentStylesheet(new Dracula().getUserAgentStylesheet());

      app.scene().getStylesheets().add(cssPath);
        primaryStage.setScene(app.scene());
        primaryStage.show();
        
    
    }

   // public static Session hibernate(){
   //     SessionFactory sessionFactory;
   //     var config = new Configuration().configure()
   //     .addAnnotatedClass(JewelryObject.class)
   //     .addAnnotatedClass(BuyPercentageObject.class)
   //     .addAnnotatedClass(BuyCaratagePercentagesObject.class)
   //     .addAnnotatedClass(MetalPricesObject.class)
   //     .addAnnotatedClass(CurrencyPricesObject.class)
   //     .addAnnotatedClass(ConstantsObject.class)
   //     .addAnnotatedClass(BuyJewelryObject.class)
   //             .addAnnotatedClass(LoanJewelryObject.class)
   //             .addAnnotatedClass(ClientObject.class);
   //     sessionFactory = config.buildSessionFactory();
   //     return  sessionFactory.openSession();
   // }
    
}
