/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import atlantafx.base.theme.*;
import org.example.entity.UserEntity;
import org.example.pages.LoginPage;
import org.hibernate.Session;

import javafx.application.Application;
import javafx.stage.Stage;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.jenvy.view.router.*;


public class App extends Application {
   public static Session session;

   public static boolean offline = true;

    public static void main(String[] args) {

        session = hibernate();
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {


        Page page = new LoginPage();
        PageFactory factory = new DefaultPageFactory();
        PageContainer container = new DefaultPageContainer();
        PageProvider provider = new DefaultPageProvider(container, factory, page);
        org.jenvy.App app = new org.jenvy.App(provider);


        primaryStage.setMaximized(true);
        String cssPath = getClass().getResource("/styles/style.css").toExternalForm();
        Application.setUserAgentStylesheet(new PrimerLight().getUserAgentStylesheet());
        app.scene().getStylesheets().add(cssPath);
        primaryStage.setScene(app.scene());
        primaryStage.show();
        
    
    }

   public static Session hibernate(){
       SessionFactory sessionFactory;
       var config = new Configuration().configure()
       .addAnnotatedClass(UserEntity.class);
       sessionFactory = config.buildSessionFactory();
       return  sessionFactory.openSession();
   }
    
}
