/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import atlantafx.base.theme.*;
import org.example.pages.LoginPage;
import org.hibernate.Session;

import javafx.application.Application;
import javafx.stage.Stage;
import org.jenvy.view.router.*;


public class App extends Application {
   private Session session;

    public static void main(String[] args) {
        
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {


        Page page = new LoginPage();
        PageFactory factory = new DefaultPageFactory();
        PageContainer container = new DefaultPageContainer();
        PageProvider provider = new DefaultPageProvider(container, factory, page);
        org.jenvy.App app = new org.jenvy.App(provider);


        primaryStage.setMaximized(true);
        String cssPath = getClass().getResource("/styles/style.css").toExternalForm();
        Application.setUserAgentStylesheet(new PrimerLight().getUserAgentStylesheet());
        app.scene().getStylesheets().add(cssPath);
        primaryStage.setScene(app.scene());
        primaryStage.show();
        
    
    }

   // public static Session hibernate(){
   //     SessionFactory sessionFactory;
   //     var config = new Configuration().configure()
   //     .addAnnotatedClass(JewelryObject.class)
   //     .addAnnotatedClass(BuyPercentageObject.class)
   //     .addAnnotatedClass(BuyCaratagePercentagesObject.class)
   //     .addAnnotatedClass(MetalPricesObject.class)
   //     .addAnnotatedClass(CurrencyPricesObject.class)
   //     .addAnnotatedClass(ConstantsObject.class)
   //     .addAnnotatedClass(BuyJewelryObject.class)
   //             .addAnnotatedClass(LoanJewelryObject.class)
   //             .addAnnotatedClass(ClientObject.class);
   //     sessionFactory = config.buildSessionFactory();
   //     return  sessionFactory.openSession();
   // }
    
}
